### ISSUE TITLE
[Bug]: Imcompatability between Comforts and this mod[FORGE]

### ISSUE THREAD

**Issue by BlackWarrior2004** [someaddons/dusk#10]
### Describe the bug you're experiencing

I have comforts and this mod, when I try to sleep with the sleeping bag, I can sleep at the regular time

### Reproducability

Put dusk-1.19.1-2.2 and comforts-forge-6.0.1+1.19.2, boot up world, try to sleep with the comforts sleeping bag at normal sleeping time and voila
![2022-09-21_19 25 36](https://user-images.githubusercontent.com/83131147/191582474-93fcf662-fbb2-4a08-916f-5877f30160ea.png)
this pic shows that u can sleep at regular time(check time in journey map)

Note: I am using a dedicated server with a client, not sp

Debug Log -> https://gist.github.com/BlackWarrior2004/605a8f6a37c4f05475bcaa832a2f2ef4
Latest Log -> https://gist.github.com/BlackWarrior2004/69cfecf5d3c6df1fb44e67b36f163345

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

Latest log: https://gist.github.com/BlackWarrior2004/69cfecf5d3c6df1fb44e67b36f163345

**Comment by someaddons** [comment]
should be fixed in v2.4
