### ISSUE TITLE
Probably incompability with Spawncap Control Utility (Forge & Fabric)

### ISSUE THREAD

**Issue by ghost** [someaddons/dusk#11]
I'm not sure about this because my testing was very limited, but from what I can see, monsters cap is not working when Dusk in enabled. Even when it's daytime. My enviroment of testing: Fabric loader 0.14.19 with Minecraft 1.19.3 and latest version installed for both mods

**Comment by someaddons** [comment]
if you change the spawn cap you also need to adjust the base value in dusk's config
