### ISSUE TITLE
[Bug]: Sleep Time only works on first night

### ISSUE THREAD

**Issue by Squidney64** [someaddons/dusk#13]
### Describe the bug you're experiencing

I have the minimum sleep time set to the default settings and was doing some testing. I have this mod on a server with my friends and it doesn't work properly.
I went into a singleplayer world and tested it out. The game wouldn't let me sleep until 14500 on the first night, but every night afterwards, it would allow me to sleep normally. So the time at which the game allows you to sleep is only working on the first night.

### Reproducability

1. Open new world with commands
2. Place bed
3. /gamerule doDaylightCycle false
4. /time set night
5. Try to sleep and it won't let you
6. /time add 24000 (switches to the same time on the next day)
7. Try to sleep and you can sleep

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Fabric

### Logs

https://gist.github.com/Squidney64/08c17ea47ad723430cc9383b1bd5588d

**Comment by someaddons** [comment]
fixed
