### ISSUE TITLE
[Bug]: Dusk is incompatible with mod that allow sleeping at day

### ISSUE THREAD

**Issue by Cheaterpaul** [someaddons/dusk#14]
## Correct sleep event
Your sleep time check should be done in the appropriated event.
https://github.com/someaddons/dusk/blob/3aaafa0bfdc0bf2764620cb9ed1a502d2b033a80/src/main/java/com/dusk/event/EventHandler.java#L74-L92

The `PlayerSleepInBedEvent` is not supposed to check the sleep time. For that there is the dedicated `SleepingTimeCheckEvent`. This way your sleep time is compatible with other mods.

Besides the time check `(event.getEntity().level().getDayTime() % 24000) < Dusk.config.getCommonConfig().minSleepTime.get()` the rest is fine in the `PlayerSleepInBedEvent` event

## Problem with sleeping time
I do not know if this is intended or overlooked, but some mods allow player to sleep at day, which is completely ignored by this mod. I do not know how this should be solved correctly, maybe you have an idea.

### Reproducability

^^

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

source code

**Comment by someaddons** [comment]
Its simple to solve, if you want to allow day sleeping just move the minimum day time in the config to an earlier point, 0 to disable^^
Changed the even in 3.3
