### ISSUE TITLE
[Bug]: Config file doesnt generate

### ISSUE THREAD

**Issue by SkullDiamond** [someaddons/dusk#16]
### Describe the bug you're experiencing

Config file doesnt generate

### Reproducability

I installed the mods in a fresh profile and the config is nowhere to be find

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/SkullDiamond/f9574226d7eb5ba251768902c6fc1048

**Comment by someaddons** [comment]
update the cupboard version, works fine for me on 1.4, config file generates in config/dusk.json
