### ISSUE TITLE
[Bug]: Causes spawn point to be set when using a sleeping bag.

### ISSUE THREAD

**Issue by ProsperCraft** [someaddons/dusk#17]
### Describe the bug you're experiencing

https://github.com/illusivesoulworks/comforts/issues/124

### Reproducability

install comforts(perhaps any mod that adds sleeping bags that don't set your spawn point but cause sleep) then click with the bag on the ground.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://github.com/illusivesoulworks/comforts/issues/124

**Comment by someaddons** [comment]
fixed in 3.4
