### ISSUE TITLE
[Bug]: 1.20.1

### ISSUE THREAD

**Issue by Krimatoria** [someaddons/dusk#18]
### Describe the bug you're experiencing

In the new version, you cannot put a label on the rebirth point on the bed, only at night, in version 3.5 everything works fine. I had to roll it back.

### Reproducability

Just install a new version and check the operation of the bed.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1,20,1

### Modloader version

Forge

### Logs

.

**Comment by someaddons** [comment]
fixed in 3.7

**Comment by Karashok-Leo** [comment]
1.20.1 fabric plz?
