### ISSUE TITLE
Incompability with Somnia Awoken

### ISSUE THREAD

**Issue by TurklerRS** [someaddons/dusk#6]
**Describe the bug**
https://www.curseforge.com/minecraft/mc-mods/somnia
Using both mods together completely stops the player from sleeping. I'm almost certain this is because both mods try to change when the player can sleep.

**To Reproduce**
1. Try to sleep

**Expected behavior**
Well, sleep obviously.

** Mod version **
dusk-1.4.jar for 1.16.5

**Comment by someaddons** [comment]
should be able to solve it via config, dusk is very simple if that doesnt work then the other mod does some wonky stuff and probably needs to fix it on their side
