### ISSUE TITLE
[Bug]: Incompatibility with all your mods, along with many others

### ISSUE THREAD

**Issue by foul-fortune-feline** [someaddons/dusk#7]
### Describe the bug you're experiencing

You need to update the modid of your mods. Them all being "modid" isn't conducive to compatibility.

As a sidenote, I recommend you clean up other fabric examplemod stuff

### Reproducability

Try to install any two mods you made at the same time

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Fabric

### Logs

irrelevant.

**Comment by foul-fortune-feline** [comment]
Ah upon decompile I see it's smth u've only done with ur untouched metadata files, hrm

**Comment by someaddons** [comment]
Only thing thats not adjust is the default assets/icon file everything else has a proper ID

**Comment by foul-fortune-feline** [comment]
Yea I can't figure exactly what the issue is, I'll post a stacktrace when I get around to it
