### ISSUE TITLE
[Bug]: Forge version of the mod is not functioning (minecraft 1.18.2)

### ISSUE THREAD

**Issue by Dyshonored** [someaddons/dusk#9]
### Describe the bug you're experiencing

I used forge 40.1.20 on minecraft 1.18.2 with only this mod (the forge 1.18.2 version ofc) for testing and found that the mob cap is always the vanilla 70 no matter the setting in the config file.

### Reproducability

Change the baseMonsterCap setting found in config file to 100
Run minecraft with the forge version of this mod on forge 40.1.20 (minecraft 1.18.2)
Toggle F3 info and look at the current mob count (for monsters). It is still capped at the vanilla value (70).

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

<script src="https://gist.github.com/Dyshonored/0f895e36c89d64a300bc99102348f492.js"></script>

**Comment by someaddons** [comment]
the mobcap change works just fine, modifications only start to happen when its getting night and gradually increase.
